### PR TITLE
fixed refactoring for `serializedStringTuples1`

### LINKED ISSUE #241: Refactor `serializedStringTuples` used in the index
Refactor the type along with its methods. Make them more readable, rename variables currently, it's confusing. https://github.com/prometheus/tsdb/blob/master/index/index.go#L929-L933

### PR DESCRIPTION
**Pull request by knrt10**
closes #241. @krasi-georgiev would you please review and tell is this what you want?

### CODE REVIEW

File: index/index.go [hunk 1]
```diff
@@ -929,8 +929,8 @@ func (r *Reader) Postings(name, value string) (Postings, error) {
 
 // SortedPostings returns the given postings list reordered so that the backing series
 // are sorted.
-func (r *Reader) SortedPostings(p Postings) Postings {
-	return p
+func (r *Reader) SortedPostings(post Postings) Postings {
+	return post
```
Comment (krasi-georgiev) [inline index/index.go]: when we use a variable in the next 1-2 lines it is fine to have it as a single letter.

File: index/index.go [hunk 2]
```diff
@@ -868,9 +868,9 @@ func (r *Reader) LabelValues(names ...string) (StringTuples, error) {
 		return nil, errors.Wrap(d.err(), "read label value index")
 	}
 	st := &serializedStringTuples{
-		l:      nc,
-		b:      d.get(),
-		lookup: r.lookupSymbol,
+		length:  nc,
+		breadth: d.get(),
```
Comment (krasi-georgiev) [inline index/index.go]: what does `breadth` stand for?

File: index/index.go [hunk 3]
```diff
@@ -868,9 +868,9 @@ func (r *Reader) LabelValues(names ...string) (StringTuples, error) {
 		return nil, errors.Wrap(d.err(), "read label value index")
 	}
 	st := &serializedStringTuples{
-		l:      nc,
-		b:      d.get(),
-		lookup: r.lookupSymbol,
+		length:  nc,
```
Comment (krasi-georgiev) [inline index/index.go]: I need to read the code deeper, but I think this represents a the 32 bit big Indian version and not a length.

File: index/index.go (hunk 1 above)
Comment (knrt10) [reply index/index.go]: Ok, will change it.

File: index/index.go (hunk 2 above)
Comment (knrt10) [reply index/index.go]: I was confused as [here](https://github.com/prometheus/tsdb/pull/377/files#diff-71ebe2bcf31a915b1fa3b3b289d5d31dR977) in the definition of struct **serializedStringTuples** it was previously slice of bytes and didn't knew what it should be. What do you suggest should I change it to?

File: index/index.go (hunk 3 above)
Comment (knrt10) [reply index/index.go]: I thought as according to [here](https://github.com/prometheus/tsdb/blob/3df5bcf39e9fb4dea3f70f9ec2bcb77c23271268/index/index.go#L937). What should I change it too?

File: index/index.go (hunk 2 above)
Comment (knrt10) [reply index/index.go]: @krasi-georgiev after reading code deeper and some [go doc](https://golang.org/pkg/encoding/binary/#example_ByteOrder_get) I found that its not `breadth` its just **slices of binary data**. So instead of binary I changes it to *binSlice*. And *l* can be used as length because it is just size of serializedString tuple. I am saying beacause [here](https://github.com/prometheus/tsdb/blob/master/index/index.go#L864) **nc** is being initialized as `be32int` that is an integer returned from [here](https://github.com/prometheus/tsdb/blob/master/index/encoding_helpers.go#L78). And also we are using **l** just to iterate [here](https://github.com/prometheus/tsdb/blob/master/index/index.go#L991). So as per me *lenght* is just fine. If you suggest anything else I can change it to that. I have pushed latest changes please review.

Comment (knrt10) [reply index/index.go]: @krasi-georgiev updated.

**Comment by krasi-georgiev** [comment]
@knrt10 while we are on the topic , should we also update the `stringTuples` struct field names?

**Comment by knrt10** [comment]
> @knrt10 while we are on the topic , should we also update the `stringTuples` struct field names?

Yes on it.

**Comment by krasi-georgiev** [comment]
not sure , look at the implementation.

**Comment by knrt10** [comment]
> not sure , look at the implementation.

Ok let me check

**Comment by knrt10** [comment]
@krasi-georgiev I have changed it to 
```
type stringTuples struct {
	tupLength int      // tuple length
	tupSlice  []string // flattened tuple entries
}
```
is it ok?

**Comment by krasi-georgiev** [comment]
I think so , 
now we don't even need the additional comments as the var name is good enough to understand its purpose.

**Comment by krasi-georgiev** [comment]
Now that I see it stutters a bit. Lets try as:
```
type stringTuples struct {
	length int      // tuple length
	entries  []string // flattened tuple entries
}
```

**Comment by knrt10** [comment]
Do i have to leave the comment as it is or remove them?

**Comment by krasi-georgiev** [comment]
lets leave it.

**Comment by knrt10** [comment]
Updated

**Comment by krasi-georgiev** [comment]
shall we also change `idsSlice -> idsEntries` to make it consistent?

**Comment by knrt10** [comment]
Yep, updated

**Comment by krasi-georgiev** [comment]
@gouthamve what do you think does this change makes it more clear?

**Comment by knrt10** [comment]
@krasi-georgiev any updates on this?

**Comment by krasi-georgiev** [comment]
still waiting for @gouthamve to confirm.
This will  take few days as we have some more urgent  bugfixes.

**Comment by krasi-georgiev** [comment]
ping @gouthamve

**Comment by krasi-georgiev** [comment]
seems @gouthamve is busy putting out fires in other places :stuck_out_tongue: 
@codesome could you take a look

File: index/index.go [hunk 4]
```diff
@@ -973,23 +973,23 @@ func (t *stringTuples) Less(i, j int) bool {
 }
 
 type serializedStringTuples struct {
-	l      int
-	b      []byte
-	lookup func(uint32) (string, error)
+	idsCount   int
+	idsEntries []byte
```
Comment (codesome) [inline index/index.go]: As this is not exactly entries but the bytes containing them, I would ideally name them `idsBytes` (previous naming was `b`, I guess it meant bytes).

It was not totally clear why prefix is `ids` (later saw the comments). Can you add a comment saying these bytes contains the ids pointing to actual string in the lookup table.

Comment (krasi-georgiev) [reply index/index.go]: yep +1 on both comments.

Comment (knrt10) [reply index/index.go]: So @krasi-georgiev what should I do? Please don't mind me asking as I don't quite fully understand.

Comment (krasi-georgiev) [reply index/index.go]:
```
idsBytes []byte // bytes containing the ids pointing to the string in the lookup table.
```

Comment (knrt10) [reply index/index.go]: Updated
