### PR TITLE
Fix #191

### LINKED ISSUE #191: Compact failed error in windows environment
tsdb did not close file before rename it case "compaction failed" on windows.

https://github.com/prometheus/tsdb/blob/f347eac33d3e0e9a8ab67cd12d7e99b58dd84155/tombstones.go#L43

see:
[https://github.com/prometheus/prometheus/issues/3253](https://github.com/prometheus/prometheus/issues/3253)

### PR DESCRIPTION
**Pull request by ranbochen**
#191

Fix remove file issue on windows, when compact blocks(block count > 1)

Need find a better way to handle windows file operations! It's hard to find which file must be closed!

### CODE REVIEW

**Comment by ranbochen** [comment]
after this patch, it work on my windows server now.

@fabxc

**Comment by grobie** [comment]
@beorn7

**Comment by beorn7** [comment]
Do we have a qualified reviewer for this? @fabxc @Gouthamve ?
This looks like it should go into rc3 . (I assume we don't want to release something that doesn't work on MS Windows?)

File: db.go [hunk 1]
```diff
@@ -379,6 +379,27 @@ func (db *DB) compact() (changes bool, err error) {
...
+				}
+			}
+			if keep {
+				blocks = append(blocks, b)
+			} else {
+				b.Close()
+			}
+		}
+		db.blocks = blocks
+		db.mtx.Unlock()
```
Comment (fabxc) [inline db.go]: This will cause data for the given time range to become unavailable until the reload, which is called later gets completed.

Also, introspecting `db.blocks` in this code path kinda throws a few things together that were separated before.

But I suppose windows not allowing us to delete open files literally forces us to have this small blip where data is not accessible. Anyone sees a way around this?

**Comment by fabxc** [comment]
I'll merge this now – maybe we can find an alternative way for the described problem in the future.
