### PR TITLE
Fix various races

### LINKED ISSUE #139: Data race in 0db4c227b between tsdb.(*headAppender).AddFast() and tsdb.(*memSeries).truncateChunksBefore()
Apologies if this has been discussed already (it may be related to #137?) but raising an issue in case it helps with debugging.

I'm using tsdb as a library and found it would occasionally panic.

I'm able to reliably reproduce the issue against 0db4c227b by enabling the race detector on the benchmark utility, e.g.:

```
matt➜github.com/prometheus/tsdb(master)» go run -race cmd/tsdb/main.go bench write testdata/20k.series
>> start stage=readData
>> completed stage=readData duration=1.366588453s
>> start stage=ingestScrapes
==================
WARNING: DATA RACE
Read at 0x00c4200f63c8 by goroutine 20:
  github.com/prometheus/tsdb.(*SegmentWAL).LogSamples()
      /Users/matt/go/src/github.com/prometheus/tsdb/wal.go:435 +0x1f3
  github.com/prometheus/tsdb.(*headAppender).Commit()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:431 +0x180
  github.com/prometheus/tsdb.dbAppender.Commit()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:305 +0x42
  github.com/prometheus/tsdb.(*dbAppender).Commit()
      <autogenerated>:1 +0x7a
  main.(*writeBenchmark).ingestScrapesShard()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:243 +0x8c4
  main.(*writeBenchmark).ingestScrapes.func1()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:178 +0xab

Previous write at 0x00c4200f63c8 by goroutine 21:
  [failed to restore the stack]

Goroutine 20 (running) created at:
  main.(*writeBenchmark).ingestScrapes()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:177 +0x18f
  main.(*writeBenchmark).run.func2()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:142 +0xb2
  main.measureTime()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:309 +0x13d
  main.(*writeBenchmark).run()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:140 +0x5c3
  main.(*writeBenchmark).(main.run)-fm()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:85 +0x69
  github.com/spf13/cobra.(*Command).execute()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:653 +0x888
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:728 +0x40b
  github.com/spf13/cobra.(*Command).Execute()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:687 +0x38
  main.main()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:54 +0x1f3

Goroutine 21 (running) created at:
  main.(*writeBenchmark).ingestScrapes()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:177 +0x18f
  main.(*writeBenchmark).run.func2()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:142 +0xb2
  main.measureTime()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:309 +0x13d
  main.(*writeBenchmark).run()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:140 +0x5c3
  main.(*writeBenchmark).(main.run)-fm()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:85 +0x69
  github.com/spf13/cobra.(*Command).execute()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:653 +0x888
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:728 +0x40b
  github.com/spf13/cobra.(*Command).Execute()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:687 +0x38
  main.main()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:54 +0x1f3
==================
ts=2017-09-07T21:59:12.391082889Z caller=compact.go:360 msg="compact blocks" count=1 mint=0 maxt=7200000
==================
WARNING: DATA RACE
Write at 0x00c422f23538 by goroutine 16:
  github.com/prometheus/tsdb.(*memSeries).truncateChunksBefore()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:1136 +0x1da
  github.com/prometheus/tsdb.(*stripeSeries).gc()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:960 +0x102
  github.com/prometheus/tsdb.(*Head).gc()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:519 +0xb7
  github.com/prometheus/tsdb.(*Head).Truncate()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:261 +0x190
  github.com/prometheus/tsdb.(*DB).reload()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:499 +0xb32
  github.com/prometheus/tsdb.(*DB).compact()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:352 +0x4aa
  github.com/prometheus/tsdb.(*DB).run()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:257 +0x50f

Previous read at 0x00c422f23538 by goroutine 65:
  [failed to restore the stack]

Goroutine 16 (running) created at:
  github.com/prometheus/tsdb.Open()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:221 +0x85d
  main.(*writeBenchmark).run()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:113 +0x336
  main.(*writeBenchmark).(main.run)-fm()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:85 +0x69
  github.com/spf13/cobra.(*Command).execute()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:653 +0x888
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:728 +0x40b
  github.com/spf13/cobra.(*Command).Execute()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:687 +0x38
  main.main()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:54 +0x1f3

Goroutine 65 (running) created at:
  main.(*writeBenchmark).ingestScrapes()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:177 +0x18f
  main.(*writeBenchmark).run.func2()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:142 +0xb2
  main.measureTime()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:309 +0x13d
  main.(*writeBenchmark).run()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:140 +0x5c3
  main.(*writeBenchmark).(main.run)-fm()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:85 +0x69
  github.com/spf13/cobra.(*Command).execute()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:653 +0x888
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:728 +0x40b
  github.com/spf13/cobra.(*Command).Execute()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:687 +0x38
  main.main()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:54 +0x1f3
==================
==================
WARNING: DATA RACE
Write at 0x00c4233e1ef8 by goroutine 16:
  github.com/prometheus/tsdb.(*memSeries).truncateChunksBefore()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:1136 +0x1da
  github.com/prometheus/tsdb.(*stripeSeries).gc()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:960 +0x102
  github.com/prometheus/tsdb.(*Head).gc()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:519 +0xb7
  github.com/prometheus/tsdb.(*Head).Truncate()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:261 +0x190
  github.com/prometheus/tsdb.(*DB).reload()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:499 +0xb32
  github.com/prometheus/tsdb.(*DB).compact()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:352 +0x4aa
  github.com/prometheus/tsdb.(*DB).run()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:257 +0x50f

Previous read at 0x00c4233e1ef8 by goroutine 65:
  github.com/prometheus/tsdb.(*headAppender).AddFast()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:1212 +0xbb
  github.com/prometheus/tsdb.(*dbAppender).AddFast()
      <autogenerated>:1 +0x7f
  main.(*writeBenchmark).ingestScrapesShard()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:228 +0x4d8
  main.(*writeBenchmark).ingestScrapes.func1()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:178 +0xab

Goroutine 16 (running) created at:
  github.com/prometheus/tsdb.Open()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:221 +0x85d
  main.(*writeBenchmark).run()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:113 +0x336
  main.(*writeBenchmark).(main.run)-fm()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:85 +0x69
  github.com/spf13/cobra.(*Command).execute()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:653 +0x888
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:728 +0x40b
  github.com/spf13/cobra.(*Command).Execute()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:687 +0x38
  main.main()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:54 +0x1f3

Goroutine 65 (running) created at:
  main.(*writeBenchmark).ingestScrapes()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:177 +0x18f
  main.(*writeBenchmark).run.func2()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:142 +0xb2
  main.measureTime()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:309 +0x13d
  main.(*writeBenchmark).run()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:140 +0x5c3
  main.(*writeBenchmark).(main.run)-fm()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:85 +0x69
  github.com/spf13/cobra.(*Command).execute()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:653 +0x888
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:728 +0x40b
  github.com/spf13/cobra.(*Command).Execute()
      /Users/matt/go/src/github.com/spf13/cobra/command.go:687 +0x38
  main.main()
      /Users/matt/go/src/github.com/prometheus/tsdb/cmd/tsdb/main.go:54 +0x1f3
==================
<...snip...>
```

I'm assuming that the benchmark utility applies the appropriate locks.

I was able to reproduce the issue with the following code, however I'm not sure if multiple appenders are intended to be used concurrently (there's a [comment](https://github.com/prometheus/tsdb/blob/0db4c227b72145418ad4c1fbda8fdb87bfe77a02/db.go#L69) on the interface but it's not clear to me if that applies to multiple appenders):

```go
package main

import (
	"time"

	"github.com/prometheus/tsdb"
	"github.com/prometheus/tsdb/labels"
)

func main() {
	st, err := tsdb.Open("data", nil, nil, &tsdb.Options{
		WALFlushInterval:  200 * time.Millisecond,
		RetentionDuration: 15 * 24 * 60 * 60 * 1000, // 15 days in milliseconds
		BlockRanges:       tsdb.ExponentialBlockRanges(2*60*60*1000, 3, 5),
	})
	if err != nil {
		panic(err)
	}

	append := func() {
		app := st.Appender()
		_, err := app.Add(labels.Labels{labels.Label{"__name__", "foo"}}, 10000, 1.0)
		if err != nil {
			panic(err)
		}
		if err := app.Commit(); err != nil {
			panic(err)
		}
	}

	for i := 0; i < 1000; i++ {
		go append()
	}
}
```

...which results in errors such as:

```
==================
WARNING: DATA RACE
Write at 0x00c420162038 by goroutine 15:
  github.com/prometheus/tsdb.(*memSeries).cut()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:1073 +0x297
  github.com/prometheus/tsdb.(*memSeries).append()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:1151 +0x581
  github.com/prometheus/tsdb.(*headAppender).Commit()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:438 +0x256
  github.com/prometheus/tsdb.(*initAppender).Commit()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:327 +0x6e
  github.com/prometheus/tsdb.dbAppender.Commit()
      /Users/matt/go/src/github.com/prometheus/tsdb/db.go:305 +0x42
  github.com/prometheus/tsdb.(*dbAppender).Commit()
      <autogenerated>:1 +0x7a
  main.main.func1()
      /Users/matt/go/src/github.com/mattbostock/tsdb_test/main.go:26 +0x17b

Previous read at 0x00c420162038 by goroutine 761:
  github.com/prometheus/tsdb.(*headAppender).AddFast()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:1212 +0xbb
  github.com/prometheus/tsdb.(*headAppender).Add()
      /Users/matt/go/src/github.com/prometheus/tsdb/head.go:396 +0x181
  github.com/prometheus/tsdb.(*dbAppender).Add()
      <autogenerated>:1 +0x9f
  main.main.func1()
      /Users/matt/go/src/github.com/mattbostock/tsdb_test/main.go:22 +0x129

Goroutine 15 (running) created at:
  main.main()
      /Users/matt/go/src/github.com/mattbostock/tsdb_test/main.go:32 +0x256

Goroutine 761 (running) created at:
  main.main()
      /Users/matt/go/src/github.com/mattbostock/tsdb_test/main.go:32 +0x256
```

```
matt➜github.com/mattbostock/tsdb_test» go run -race main.go
panic: invalid magic header 0 in "data/wal/000004"

goroutine 1 [running]:
main.main()
	/Users/matt/go/src/github.com/mattbostock/tsdb_test/main.go:17 +0x32a
exit status 2
```

```
matt➜github.com/mattbostock/tsdb_test» go run -race main.go
panic: validate meta "data/wal/000003": EOF

goroutine 1 [running]:
main.main()
	/Users/matt/go/src/github.com/mattbostock/tsdb_test/main.go:17 +0x32a
exit status 2
```

### PR DESCRIPTION
**Pull request by fabxc**
Fixes #139 

@mattbostock

### CODE REVIEW

File: head.go [hunk 1]
```diff
@@ -402,9 +402,11 @@ func (a *headAppender) AddFast(ref uint64, t int64, v float64) error {
 	if s == nil {
 		return errors.Wrap(ErrNotFound, "unknown series")
 	}
+	s.Lock()
 	if err := s.appendable(t, v); err != nil {
 		return err
```
Comment (mdlayher) [inline head.go]: Appears you're not releasing the mutex in the event of an error here.

Comment (fabxc) [reply head.go]: Thanks!

**Comment by mattbostock** [comment]
Thanks! Apologies I wasn't able to help review this due to lack of time this week.
